In [3]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [6]:
m = 2*np.arange(16).reshape(4,4) - 1
m[np.diag_indices_from(m)] = 0
m

array([[ 0,  1,  3,  5],
       [ 7,  0, 11, 13],
       [15, 17,  0, 21],
       [23, 25, 27,  0]])

In [19]:
idx = ~np.eye(*m.shape, dtype=np.bool)
idx

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]], dtype=bool)

In [21]:
m.T[idx]

array([ 7, 15, 23,  1, 17, 25,  3, 11, 27,  5, 13, 21])

In [37]:
stack0 = lambda m: m.T[np.ones(m.size, dtype=np.bool).reshape(*m.shape)]
stack00 = lambda m: m.reshape(m.size, -1)
stack1 = lambda mat: np.squeeze(np.concatenate(np.hsplit(mat, range(1, mat.shape[1]))))

In [33]:
%%timeit
for i in range(1, 60):
    m = 2*np.arange(i**2).reshape(i, i) - 1
    _ = stack0(m)

100 loops, best of 3: 2.63 ms per loop


In [34]:
%%timeit
for i in range(1, 60):
    m = 2*np.arange(i**2).reshape(i, i) - 1
    _ = stack1(m)

100 loops, best of 3: 10.5 ms per loop


In [35]:
%%timeit
for i in range(1, 60):
    m = 2*np.arange(i**2).reshape(i, i) - 1
    _ = stack00(m)

100 loops, best of 3: 2.17 ms per loop


In [38]:
for i in range(1, 60):
    m = 2*np.arange(i**2).reshape(i, i) - 1
    assert np.allclose(stack0(m), stack00(m))

AssertionError: 