In [2]:
import numpy as np
from sklearn import model_selection

In [76]:
from sklearn.model_selection import StratifiedShuffleSplit
N = 50
X = np.arange(2*N).reshape((N, 2))
y = (np.random.rand(N) < 0.5).astype(int)
sss = StratifiedShuffleSplit(n_splits=3, test_size=0.2, random_state=0)
sss.get_n_splits(X, y)
print(sss, end='\n\n\n\n')
xtrain_list = list()
xtest_list = list()
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index, end='\n\n')
    X_train, X_test = X[train_index], X[test_index]
    xtrain_list.append(train_index)
    xtest_list.append(test_index)
    y_train, y_test = y[train_index], y[test_index] 
    print("X_val:\n", *np.unique(X_train, return_counts=True), '\n', *np.unique(X_test, return_counts=True), end='\n')
    print("y_val:\n", *np.unique(y_train, return_counts=True), '\n', *np.unique(y_test, return_counts=True), end='\n\n\n\n\n') 

StratifiedShuffleSplit(n_splits=3, random_state=0, test_size=0.2,
            train_size=None)



TRAIN: [14 29 11 38 42 17  8 16 10  3 35 25 24 31 13  2 21 36 22  9 47  7 41 27 37
 49 33 32 40 43 46 45 15  4 20 19 30 26 18 12] TEST: [ 0  6  1 44 23  5 48 39 34 28]

X_val:
 [ 4  5  6  7  8  9 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 48 49 50 51 52 53 54 55 58 59 60 61
 62 63 64 65 66 67 70 71 72 73 74 75 76 77 80 81 82 83 84 85 86 87 90 91 92
 93 94 95 98 99] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1] 
 [ 0  1  2  3 10 11 12 13 46 47 56 57 68 69 78 79 88 89 96 97] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
y_val:
 [0 1] [25 15] 
 [0 1] [6 4]




TRAIN: [21 47 35  2  9 40 46  1 36  4 39 48 10 12 25 42 34 16  7 32 17 29  3 33 31
  5 15 18 14 11 27 22 49 43  8 30 23 19 13 45] TEST: [41  6 44  0 28 37 26 24 20 38]

X

In [77]:
xtr = np.concatenate(xtrain_list)
xte = np.concatenate(xtest_list)

In [78]:
x

[array([ 0,  6,  1, 44, 23,  5, 48, 39, 34, 28]),
 array([41,  6, 44,  0, 28, 37, 26, 24, 20, 38]),
 array([ 3, 38, 40, 36, 17,  1,  0, 39, 10, 26])]

In [79]:
xte

array([ 0,  6,  1, 44, 23,  5, 48, 39, 34, 28, 41,  6, 44,  0, 28, 37, 26,
       24, 20, 38,  3, 38, 40, 36, 17,  1,  0, 39, 10, 26])

In [80]:
from collections import Counter

In [89]:
Counter(xte).most_common(10)

[(0, 3),
 (6, 2),
 (1, 2),
 (44, 2),
 (39, 2),
 (28, 2),
 (26, 2),
 (38, 2),
 (23, 1),
 (5, 1)]

In [88]:
Counter(xtr).most_common(10)

[(14, 3),
 (29, 3),
 (11, 3),
 (42, 3),
 (8, 3),
 (16, 3),
 (35, 3),
 (25, 3),
 (31, 3),
 (13, 3)]